format = """
$time\
$username\
$hostname\
$directory\
${custom.jj}\
$git_state\
$cmd_duration\
$line_break\
$python\
$character"""

[directory]
style = "#fabd2f"

[character]
success_symbol = "[|](#fb4934)"
error_symbol = "[|](#fb4934 bold)"
vimcmd_symbol = "[|](#b8bb26)"


[custom.jj]
disabled = false
when = "jj-starship detect"
shell = ["jj-starship"]
format = "$output "

[git_branch]
disabled = true

[git_status]
disabled = true

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "#a89984"

[cmd_duration]
format = "[$duration]($style) "
style = "#a89984"

[time]
disabled = false
format = "\\[[$time]($style)\\] "
time_format = "%H:%M"
style = "#a89984"

[python]
format = "[$virtualenv]($style) "
style = "#a89984"

