#!/usr/bin/env sh

# =================== General ==============================

#Run yabai with the scripting addition

sudo /opt/homebrew/bin/yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo /opt/homebrew/bin/yabai --load-sa"

# =================== Config ===============================

yabai -m config external_bar all:0:28

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_shadow		         off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                          bsp
yabai -m config top_padding                     0
yabai -m config bottom_padding                  0
yabai -m config left_padding                    0
yabai -m config right_padding                   0
yabai -m config window_gap                      6

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 web
setup_space 2 term
setup_space 3 code
setup_space 4 tools
setup_space 5 media
setup_space 6 float

# Space config
yabai -m config --space 6 layout float
yabai -m config --space 1 layout stack

# Unmanaged
# float system preferences

# show digital colour meter topmost and on all spaces

yabai -m rule --add app="^System Preferences$"	manage=off 
yabai -m rule --add app="^iStat Menus"		    manage=off
yabai -m rule --add app="^Stickies$"		    manage=off

# Primary
yabai -m rule --add app="Google Chrome"         space=^1

# Terminal
yabai -m rule --add app="Alacritty"             space=^2
yabai -m rule --add app="Warp"			        space=^2

# Code
yabai -m rule --add app="Code"			        space=^3
yabai -m rule --add app="Sublime Text"		    space=^3
yabai -m rule --add app="Goland"		        space=^3
yabai -m rule --add app="CLion"			        space=^3
yabai -m rule --add app="InteliJ IDEA"		    space=^3
yabai -m rule --add app="Rider"			        space=^3

# Tools
yabai -m rule --add app="Finder"		        space=^4
yabai -m rule --add app="Postman"               space=^4
yabai -m rule --add app="DataGrip"              space=^4
yabai -m rule --add app="RedisInsight-v2"       space=^4
yabai -m rule --add app="Clean My Mac"          space=^4
yabai -m rule --add app="Docker"		        space=^4
yabai -m rule --add app="Transmission"		    space=^4
yabai -m rule --add app="Todoist"		        space=^4
yabai -m rule --add app="Bitwarden"		        space=^4
yabai -m rule --add app="Slack"		            space=^4

# Social
yabai -m rule --add app="WhatsApp"              space=^5
yabai -m rule --add app="Spotify"		        space=^5
yabai -m rule --add app="IINA"			        space=^5
yabai -m rule --add app="Flow"			        space=^5

# Floating
yabai -m rule --add app="^System Preferences$"	space=^6

