#!/usr/bin/env sh

yabai -m config external_bar all:0:28

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow		     off
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xffb8bb26
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                          bsp
yabai -m config top_padding                     0
yabai -m config bottom_padding                  0
yabai -m config left_padding                    0
yabai -m config right_padding                   0
yabai -m config window_gap                      6

# Space labels
yabai -m space 1 --label "web"
yabai -m space 2 --label "term"
yabai -m space 3 --label "code"
yabai -m space 4 --label "tools"
yabai -m space 5 --label "media"
yabai -m space 6 --label "float"

# Space config
yabai -m config --space 6 layout float

# Unmanaged
# float system preferences

# show digital colour meter topmost and on all spaces

yabai -m rule --add app="^System Preferences$"	manage=off border=off
yabai -m rule --add app="^iStat Menus"		manage=off border=off

# Primary
yabai -m rule --add app="Google Chrome"         space=^1

# Terminal
yabai -m rule --add app="Alacritty"             space=^2

# Code
yabai -m rule --add app="Code"			space=^3
yabai -m rule --add app="Sublime Text"		space=^3
yabai -m rule --add app="Goland"		space=^3
yabai -m rule --add app="CLion"			space=^3
yabai -m rule --add app="InteliJ IDEA"		space=^3
yabai -m rule --add app="Rider"			space=^3

# Tools
yabai -m rule --add app="Finder"		space=^4
yabai -m rule --add app="Postman"               space=^4
yabai -m rule --add app="DataGrip"              space=^4
yabai -m rule --add app="Clean My Mac"          space=^4
yabai -m rule --add app="Docker"		space=^4
yabai -m rule --add app="Transmission"		space=^4
yabai -m rule --add app="Todoist"		space=^4

# Social
yabai -m rule --add app="WhatsApp"              space=^5
yabai -m rule --add app="Spotify"		space=^5
yabai -m rule --add app="IINA"			space=^5
yabai -m rule --add app="Flow"			space=^5

# Floating
yabai -m rule --add app="^System Preferences$"	space=^6

